version: "3.8"

services:
  craete_instance:
    build:
      context: .
    image: instance_image:latest
    command: python3 bot.py
    ports:
      - "8081:8081"  
    volumes:
      - ./oci_private_key.pem:/path/to/oci_private_key.pem
    environment:
      CONFIG_FILE_PATH: ./config.bin
    depends_on:
      - oci_registry

  oci_registry:
    image: docker.io/library/python:latest
    command: /bin/sh -c "pip install -r requirements.txt"
    volumes:
      - .:/app
    working_dir: /app
